name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/Checkout@v4

    - name: Generate hash
      id: generate_hash
      run: |
        HASH=$(echo $GITHUB_SHA | head -c7)
        echo "hash=$HASH" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t igorvinicyos/nlw.service.passin:${{ steps.generate_hash.outputs.hash }} .

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push image
      run: |
        docker push igorvinicyos/nlw.service.passin:${{ steps.generate_hash.outputs.hash }}